services:
  # ElasticSearch is removed for now
    elasticsearch:
      image: elasticsearch:8.14.0
      container_name: es01
      environment:
        - node.name=es01
        - cluster.name=es-docker-cluster
        - bootstrap.memory_lock=true
        - discovery.type=single-node
        - xpack.security.transport.ssl.enabled=false
        - xpack.security.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ports:
        - "9200:9200"
      volumes:
          - esdata:/usr/share/elasticsearch/data
          - ./install/elastic/mappings:/usr/share/elasticsearch/mappings
      healthcheck:
        test: ["CMD-SHELL", "curl -s http://elasticsearch:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
        interval: 30s
        timeout: 10s
        retries: 5

volumes:
  pgdata:
  esdata:
  grafana-data:

networks:
  bot_network:
    external: false